# Generated by Django 5.1.4 on 2026-05-16 02:14

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.UUIDField()),
                (
                    "recipe_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINALIZED", "Finalized"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meal_requests",
                "indexes": [
                    models.Index(
                        fields=["patient_id"], name="idx_meal_requests_patient"
                    ),
                    models.Index(fields=["status"], name="idx_meal_requests_status"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finalized_at__isnull", False), ("status", "FINALIZED")
                            ),
                            models.Q(("status", "FINALIZED"), _negated=True),
                            _connector="OR",
                        ),
                        name="meal_requests_finalized_has_timestamp",
                    )
                ],
            },
        ),
    ]
