# Generated by Django 5.1.4 on 2026-05-16 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recipes",
            },
        ),
        migrations.CreateModel(
            name="RecipeAllergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.CharField(
                        choices=[
                            ("MILK", "Milk"),
                            ("EGGS", "Eggs"),
                            ("FISH", "Fish"),
                            ("SHELLFISH", "Shellfish"),
                            ("TREE_NUTS", "Tree Nuts"),
                            ("PEANUTS", "Peanuts"),
                            ("WHEAT", "Wheat"),
                            ("SOY", "Soy"),
                            ("SESAME", "Sesame"),
                            ("DAIRY", "Dairy"),
                            ("GLUTEN", "Gluten"),
                            ("NUTS", "Nuts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergens",
                        to="recipe.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "recipe_allergens",
                "unique_together": {("recipe", "allergen")},
            },
        ),
        migrations.CreateModel(
            name="RecipeDietCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compatible_diet",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("LOW_SODIUM", "Low Sodium"),
                            ("DIABETIC", "Diabetic"),
                            ("LOW_FAT", "Low Fat"),
                            ("VEGAN", "Vegan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_compatibility",
                        to="recipe.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "recipe_diet_compatibility",
                "unique_together": {("recipe", "compatible_diet")},
            },
        ),
    ]
