# Generated by Django 5.1.4 on 2026-05-16 02:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("mrn", models.CharField(max_length=50, unique=True)),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("LOW_SODIUM", "Low Sodium"),
                            ("DIABETIC", "Diabetic"),
                            ("LOW_FAT", "Low Fat"),
                            ("VEGAN", "Vegan"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "admitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "current_clinical_state",
                    models.CharField(
                        choices=[
                            ("ADMITTED", "Admitted"),
                            ("IN_TREATMENT", "In Treatment"),
                            ("OBSERVATION", "Observation"),
                            ("DISCHARGED", "Discharged"),
                        ],
                        default="ADMITTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "patients",
            },
        ),
        migrations.CreateModel(
            name="PatientAllergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allergen",
                    models.CharField(
                        choices=[
                            ("MILK", "Milk"),
                            ("EGGS", "Eggs"),
                            ("FISH", "Fish"),
                            ("SHELLFISH", "Shellfish"),
                            ("TREE_NUTS", "Tree Nuts"),
                            ("PEANUTS", "Peanuts"),
                            ("WHEAT", "Wheat"),
                            ("SOY", "Soy"),
                            ("SESAME", "Sesame"),
                            ("DAIRY", "Dairy"),
                            ("GLUTEN", "Gluten"),
                            ("NUTS", "Nuts"),
                        ],
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(blank=True, max_length=20, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_allergies",
                "unique_together": {("patient", "allergen")},
            },
        ),
    ]
