# Generated by Django 5.1.4 on 2026-05-16 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tray",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meal_request_id", models.UUIDField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PREPARATION_STARTED", "Preparation Started"),
                            ("ACCURACY_VALIDATED", "Accuracy Validated"),
                            ("EN_ROUTE", "En Route"),
                            ("DELIVERED", "Delivered"),
                            ("RETRIEVED", "Retrieved"),
                        ],
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("preparation_started_at", models.DateTimeField(blank=True, null=True)),
                ("accuracy_validated_at", models.DateTimeField(blank=True, null=True)),
                ("en_route_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "trays",
                "indexes": [models.Index(fields=["status"], name="idx_trays_status")],
            },
        ),
        migrations.CreateModel(
            name="TrayStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Created"),
                            ("PREPARATION_STARTED", "Preparation Started"),
                            ("ACCURACY_VALIDATED", "Accuracy Validated"),
                            ("EN_ROUTE", "En Route"),
                            ("DELIVERED", "Delivered"),
                            ("RETRIEVED", "Retrieved"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PREPARATION_STARTED", "Preparation Started"),
                            ("ACCURACY_VALIDATED", "Accuracy Validated"),
                            ("EN_ROUTE", "En Route"),
                            ("DELIVERED", "Delivered"),
                            ("RETRIEVED", "Retrieved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("transitioned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="kitchen.tray",
                    ),
                ),
            ],
            options={
                "db_table": "tray_status_history",
                "indexes": [
                    models.Index(fields=["tray"], name="idx_tray_history_tray")
                ],
            },
        ),
    ]
